<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('employees')->insert([
            'uuid'=>'1324356478',
            'matricula' => '17121052',
            'nombre'=>'John Doe',
            'apellido_p'=>'Pérez',
            'apellido_m'=>'Segundo',
            'fecha_nac'=>'1997-10-15',
            'sexo'=>'h',
            'antiguedad'=>'2018-01-16',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Colonia 1',
            'calle'=>'calle 1',
            'num_int'=>'16',
            'num_ext'=>'596',
            'cp'=>'58512',
            'tel'=>'4434044444',
            'user_id'=>'1',
            'category_id'=>'1',
            'unit_id'=>'1',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('employees')->insert([
            'uuid'=>'1548765819',
            'matricula' => '17121056',
            'nombre'=>'Joaquín',
            'apellido_p'=>'Dimitri',
            'apellido_m'=>'Rodriguez',
            'fecha_nac'=>'1988-11-23',
            'sexo'=>'h',
            'antiguedad'=>'2019-03-02',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Colonia 1',
            'calle'=>'calle 1',
            'num_int'=>'16',
            'num_ext'=>'596',
            'cp'=>'58512',
            'tel'=>'4434044444',
            'user_id'=>'2',
            'category_id'=>'2',
            'unit_id'=>'2',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('employees')->insert([
            'uuid'=>'6666666',
            'matricula' => '17121030',
            'nombre'=>'Beatriz',
            'apellido_p'=>'Dama',
            'apellido_m'=>'Piña',
            'fecha_nac'=>'1999-03-02',
            'sexo'=>'m',
            'antiguedad'=>'2017-01-01',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Centro',
            'calle'=>'Lucha del porvenir',
            'num_int'=>'13',
            'num_ext'=>'13',
            'cp'=>'58960',
            'tel'=>'4444444444',
            'category_id'=>'1',
            'unit_id'=>'2',
            'estatus'=>'Aceptado',
            'user_id'=>'3',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('employees')->insert([
            'uuid'=>'0987654321',
            'matricula' => '17121011',
            'nombre'=>'Julián',
            'apellido_p'=>'Marín',
            'apellido_m'=>'Rendón',
            'fecha_nac'=>'1997-10-15',
            'sexo'=>'h',
            'antiguedad'=>'2018-01-16',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Colonia 3',
            'calle'=>'calle 3',
            'num_int'=>'17',
            'num_ext'=>'598',
            'cp'=>'58512',
            'tel'=>'4434044447',
            'user_id'=>'4',
            'category_id'=>'1',
            'unit_id'=>'1',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('employees')->insert([
            'uuid'=>'1987019780',
            'matricula' => '17121010',
            'nombre'=>'Dulce Mariela',
            'apellido_p'=>'Adame',
            'apellido_m'=>'García',
            'fecha_nac'=>'1997-10-15',
            'sexo'=>'m',
            'antiguedad'=>'2018-01-19',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Colonia El Problema',
            'calle'=>'calle 5',
            'num_int'=>'17',
            'num_ext'=>'500',
            'cp'=>'58512',
            'tel'=>'4434004444',
            'user_id'=>'5',
            'category_id'=>'1',
            'unit_id'=>'1',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('employees')->insert([
            'uuid'=>'1321321431',
            'matricula' => '17121003',
            'nombre'=>'Fernanda',
            'apellido_p'=>'García',
            'apellido_m'=>'Luna',
            'fecha_nac'=>'1997-11-15',
            'sexo'=>'m',
            'antiguedad'=>'2018-01-16',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Colonia Las Flores',
            'calle'=>'calle Diez',
            'num_int'=>'10',
            'num_ext'=>'10',
            'cp'=>'58512',
            'tel'=>'4431044444',
            'user_id'=>'6',
            'category_id'=>'1',
            'unit_id'=>'1',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('employees')->insert([
            'uuid'=>'1231323218',
            'matricula' => '17121001',
            'nombre'=>'Agustín',
            'apellido_p'=>'Hernández',
            'apellido_m'=>'Andrade',
            'fecha_nac'=>'1987-10-15',
            'sexo'=>'h',
            'antiguedad'=>'2018-01-16',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Colonia Centro',
            'calle'=>'Manuel Dobaldo',
            'num_int'=>'16',
            'num_ext'=>'159',
            'cp'=>'58512',
            'tel'=>'4432044424',
            'user_id'=>'7',
            'category_id'=>'1',
            'unit_id'=>'1',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('employees')->insert([
            'uuid'=>'1321321488',
            'matricula' => '17121000',
            'nombre'=>'Berenice',
            'apellido_p'=>'Solórzano',
            'apellido_m'=>'Pérez',
            'fecha_nac'=>'1994-12-15',
            'sexo'=>'m',
            'antiguedad'=>'2018-01-16',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Colonia 1',
            'calle'=>'calle 1',
            'num_int'=>'18',
            'num_ext'=>'599',
            'cp'=>'58512',
            'tel'=>'4434044777',
            'user_id'=>'8',
            'category_id'=>'1',
            'unit_id'=>'1',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('employees')->insert([
            'uuid'=>'1022346478',
            'matricula' => '17121065',
            'nombre'=>'Braulio David',
            'apellido_p'=>'López',
            'apellido_m'=>'Huerta',
            'fecha_nac'=>'2000-10-15',
            'sexo'=>'h',
            'antiguedad'=>'2018-01-16',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Colonia 1',
            'calle'=>'calle 16',
            'num_int'=>'16',
            'num_ext'=>'589',
            'cp'=>'58512',
            'tel'=>'4434054644',
            'user_id'=>'9',
            'category_id'=>'1',
            'unit_id'=>'1',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('employees')->insert([
            'uuid'=>'1324356300',
            'matricula' => '17121063',
            'nombre'=>'John Doe',
            'apellido_p'=>'Pérez',
            'apellido_m'=>'Segundo',
            'fecha_nac'=>'1997-10-15',
            'sexo'=>'h',
            'antiguedad'=>'2018-01-16',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Colonia 1',
            'calle'=>'calle 1',
            'num_int'=>'16',
            'num_ext'=>'596',
            'cp'=>'58512',
            'tel'=>'4434044444',
            'user_id'=>'10',
            'category_id'=>'1',
            'unit_id'=>'1',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('employees')->insert([
            'uuid'=>'1324356677',
            'matricula' => '17121062',
            'nombre'=>'Juan',
            'apellido_p'=>'Pérez',
            'apellido_m'=>'Ramírez',
            'fecha_nac'=>'1997-10-02',
            'sexo'=>'h',
            'antiguedad'=>'2018-01-16',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Colonia 1',
            'calle'=>'calle 1',
            'num_int'=>'16',
            'num_ext'=>'400',
            'cp'=>'58512',
            'tel'=>'4434044466',
            'user_id'=>'11',
            'category_id'=>'1',
            'unit_id'=>'1',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('employees')->insert([
            'uuid'=>'1122356478',
            'matricula' => '17121061',
            'nombre'=>'Liliana',
            'apellido_p'=>'Lua',
            'apellido_m'=>'Lagos',
            'fecha_nac'=>'1997-09-15',
            'sexo'=>'m',
            'antiguedad'=>'2018-01-16',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Colonia Lagos',
            'calle'=>'Río 2',
            'num_int'=>'16',
            'num_ext'=>'9',
            'cp'=>'58512',
            'tel'=>'4434044422',
            'user_id'=>'1',
            'category_id'=>'1',
            'unit_id'=>'1',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('employees')->insert([
            'uuid'=>'1326706478',
            'matricula' => '17121051',
            'nombre'=>'Diliana',
            'apellido_p'=>'Ortiz',
            'apellido_m'=>'Salgado',
            'fecha_nac'=>'1977-10-15',
            'sexo'=>'m',
            'antiguedad'=>'2018-01-16',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Escatologías',
            'calle'=>'Calendario',
            'num_int'=>'1',
            'num_ext'=>'16',
            'cp'=>'58512',
            'tel'=>'4434043456',
            'user_id'=>'13',
            'category_id'=>'1',
            'unit_id'=>'1',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('employees')->insert([
            'uuid'=>'1324696478',
            'matricula' => '17121050',
            'nombre'=>'Hugo',
            'apellido_p'=>'Hurtado',
            'apellido_m'=>'Sánchez',
            'fecha_nac'=>'1990-10-15',
            'sexo'=>'h',
            'antiguedad'=>'2018-01-16',
            'estado'=>'Michoacán',
            'ciudad'=>'Morelia',
            'colonia'=>'Colonia 13',
            'calle'=>'Marcos Regalado',
            'num_int'=>'11',
            'num_ext'=>'1',
            'cp'=>'58512',
            'tel'=>'4431344444',
            'user_id'=>'14',
            'category_id'=>'1',
            'unit_id'=>'1',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('employee_relative')->insert([
            'parentesco'=>'hijo',
            'ingreso_bolsa'=>'2020-01-01',
            'employee_id'=>'1',
            'relative_id'=>'3',
        ]);
    }
}
